SR = 48000
N_FFT = 256
HOP = 128
WINDOW_SAMPLE_LEN = 2 ** 15
WINDOW_SLIDE_MARGIN = WINDOW_SAMPLE_LEN - 2 ** 13
FADE_SAMPLE_LEN = 128
NEY_WAV_DIR = "dataset/ney/"
GTR_WAV_DIR = "dataset/ac_gtr/"
NEY_FEATURE_DIR = "dataset/features/ney/"
GTR_FEATURE_DIR = "dataset/features/ac_gtr/"
