SR = 48000
N_FFT = 512
HOP = 128
WINDOW_SAMPLE_LEN = 4800 * 2
FADE_SAMPLE_LEN = 100
NEY_WAV_DIR = "dataset/ney/"
GTR_WAV_DIR = "dataset/ac_gtr/"
NEY_FEATURE_DIR = "dataset/features/ney/"
GTR_FEATURE_DIR = "dataset/features/ac_gtr/"
